# -*- coding: utf-8 -*-
"""Tao file tudien.xlsx: tu dien Viet -> Sec cho Cena Checker.
Chay lai file nay se GHI DE tudien.xlsx (can than neu da sua tay!)."""
import openpyxl
from openpyxl.styles import Font, PatternFill

# (viet khong dau, viet co dau, tieng sec, nhom)
E = [
 # ============ SUA & TRUNG (mlecne-vyrobky-a-vejce, masla, vejce-a-drozdi) ============
 ("sua", "sữa", "mleko", "Sữa & trứng"),
 ("sua tuoi", "sữa tươi", "cerstve mleko", "Sữa & trứng"),
 ("sua hop", "sữa hộp", "trvanlive mleko", "Sữa & trứng"),
 ("sua tiet trung", "sữa tiệt trùng", "trvanlive mleko", "Sữa & trứng"),
 ("sua khong lactose", "sữa không lactose", "bezlaktozove mleko", "Sữa & trứng"),
 ("sua chua", "sữa chua", "jogurt", "Sữa & trứng"),
 ("sua chua uong", "sữa chua uống", "jogurtovy napoj", "Sữa & trứng"),
 ("sua dac", "sữa đặc", "kondenzovane mleko", "Sữa & trứng"),
 ("sua bot", "sữa bột", "susene mleko", "Sữa & trứng"),
 ("kem tuoi", "kem tươi", "tocena zmrzlina", "Sữa & trứng"),
 ("kem sua", "kem sữa", "smetana", "Sữa & trứng"),
 ("kem chua", "kem chua", "zakysana smetana", "Sữa & trứng"),
 ("bo", "bơ (ăn)", "maslo", "Sữa & trứng"),
 ("bo lat", "bơ lạt", "maslo", "Sữa & trứng"),
 ("bo thuc vat", "bơ thực vật", "margarin", "Sữa & trứng"),
 ("pho mai", "phô mai", "syr", "Sữa & trứng"),
 ("pho mat", "phô mát", "syr", "Sữa & trứng"),
 ("pho mai lat", "phô mai lát", "platkovy syr", "Sữa & trứng"),
 ("pho mai soi", "phô mai sợi", "strouhany syr", "Sữa & trứng"),
 ("pho mai con bo cuoi", "phô mai con bò cười", "tavene syry", "Sữa & trứng"),
 ("pho mai tuoi", "phô mai tươi", "tvaroh", "Sữa & trứng"),
 ("mozzarella", "mozzarella", "mozzarella", "Sữa & trứng"),
 ("trung", "trứng", "vejce", "Sữa & trứng"),
 ("trung ga", "trứng gà", "vejce", "Sữa & trứng"),
 ("trung cut", "trứng cút", "krepelci vejce", "Sữa & trứng"),
 ("men no", "men nở", "drozdi", "Sữa & trứng"),
 # ============ THIT - CA (maso-drubez-a-ryby, drubez, lahudky) ============
 ("thit", "thịt", "maso", "Thịt cá"),
 ("thit ga", "thịt gà", "kureci", "Thịt cá"),
 ("ga", "gà", "kureci", "Thịt cá"),
 ("ga nguyen con", "gà nguyên con", "kure cele", "Thịt cá"),
 ("uc ga", "ức gà", "kureci prsa", "Thịt cá"),
 ("dui ga", "đùi gà", "kureci stehna", "Thịt cá"),
 ("canh ga", "cánh gà", "kureci kridla", "Thịt cá"),
 ("ga tay", "gà tây", "kruti", "Thịt cá"),
 ("vit", "vịt", "kachna", "Thịt cá"),
 ("thit vit", "thịt vịt", "kachna", "Thịt cá"),
 ("thit heo", "thịt heo", "veprove", "Thịt cá"),
 ("thit lon", "thịt lợn", "veprove", "Thịt cá"),
 ("heo", "heo", "veprove", "Thịt cá"),
 ("ba chi", "ba chỉ", "veprovy bok", "Thịt cá"),
 ("ba roi", "ba rọi", "veprovy bok", "Thịt cá"),
 ("suon heo", "sườn heo", "veprova zebra", "Thịt cá"),
 ("suon", "sườn", "zebra", "Thịt cá"),
 ("vai heo", "vai heo", "veprova plec", "Thịt cá"),
 ("dui heo", "đùi heo", "veprova kyta", "Thịt cá"),
 ("thit nac", "thịt nạc", "veprova panenka", "Thịt cá"),
 ("chan gio", "chân giò", "veprove koleno", "Thịt cá"),
 ("mo heo", "mỡ heo", "sadlo", "Thịt cá"),
 ("thit bo", "thịt bò", "hovezi", "Thịt cá"),
 ("bo bit tet", "bò bít tết", "hovezi steak", "Thịt cá"),
 ("thit be", "thịt bê", "teleci", "Thịt cá"),
 ("thit cuu", "thịt cừu", "jehneci", "Thịt cá"),
 ("thit tho", "thịt thỏ", "kralik", "Thịt cá"),
 ("thit bam", "thịt bằm", "mlete maso", "Thịt cá"),
 ("thit xay", "thịt xay", "mlete maso", "Thịt cá"),
 ("gan", "gan", "jatra", "Thịt cá"),
 ("xuc xich", "xúc xích", "parky", "Thịt cá"),
 ("lap xuong", "lạp xưởng", "klobasa", "Thịt cá"),
 ("xuc xich nuong", "xúc xích nướng", "klobasa", "Thịt cá"),
 ("giam bong", "giăm bông", "sunka", "Thịt cá"),
 ("jambon", "jambon", "sunka", "Thịt cá"),
 ("thit nguoi", "thịt nguội", "sunka", "Thịt cá"),
 ("thit xong khoi", "thịt xông khói", "slanina", "Thịt cá"),
 ("salami", "salami", "salam", "Thịt cá"),
 ("pate", "pa tê", "pastika", "Thịt cá"),
 ("ca", "cá", "ryba", "Thịt cá"),
 ("ca hoi", "cá hồi", "losos", "Thịt cá"),
 ("ca ngu", "cá ngừ", "tunak", "Thịt cá"),
 ("ca thu", "cá thu", "makrela", "Thịt cá"),
 ("ca tram", "cá trắm", "amur", "Thịt cá"),
 ("ca chep", "cá chép", "kapr", "Thịt cá"),
 ("ca basa", "cá basa", "pangas", "Thịt cá"),
 ("ca trich", "cá trích", "sled", "Thịt cá"),
 ("ca mong bien", "cá mòng biển", "treska", "Thịt cá"),
 ("tom", "tôm", "krevety", "Thịt cá"),
 ("muc", "mực", "kalamary", "Thịt cá"),
 ("cua", "cua", "krab", "Thịt cá"),
 ("so diep", "sò điệp", "hrebenatky", "Thịt cá"),
 # ============ RAU CU (ovoce-a-zelenina) ============
 ("rau", "rau", "zelenina", "Rau củ"),
 ("ca chua", "cà chua", "rajcata", "Rau củ"),
 ("khoai tay", "khoai tây", "brambory", "Rau củ"),
 ("khoai lang", "khoai lang", "batat", "Rau củ"),
 ("hanh tay", "hành tây", "cibule", "Rau củ"),
 ("hanh", "hành", "cibule", "Rau củ"),
 ("hanh la", "hành lá", "jarni cibulka", "Rau củ"),
 ("toi", "tỏi", "cesnek", "Rau củ"),
 ("gung", "gừng", "zazvor", "Rau củ"),
 ("ca rot", "cà rốt", "mrkev", "Rau củ"),
 ("dua chuot", "dưa chuột", "okurka", "Rau củ"),
 ("dua leo", "dưa leo", "okurka", "Rau củ"),
 ("ot chuong", "ớt chuông", "paprika", "Rau củ"),
 ("ot", "ớt", "chilli paprička", "Rau củ"),
 ("bap cai", "bắp cải", "zeli", "Rau củ"),
 ("cai thao", "cải thảo", "cinske zeli", "Rau củ"),
 ("xa lach", "xà lách", "salat", "Rau củ"),
 ("rau bina", "rau bina (chân vịt)", "spenat", "Rau củ"),
 ("cai bo xoi", "cải bó xôi", "spenat", "Rau củ"),
 ("nam", "nấm", "houby", "Rau củ"),
 ("nam huong", "nấm hương", "shiitake", "Rau củ"),
 ("bong cai trang", "bông cải trắng", "kvetak", "Rau củ"),
 ("sup lo", "súp lơ", "kvetak", "Rau củ"),
 ("bong cai xanh", "bông cải xanh", "brokolice", "Rau củ"),
 ("bap", "bắp", "kukurice", "Rau củ"),
 ("ngo", "ngô", "kukurice", "Rau củ"),
 ("bi do", "bí đỏ", "dyne", "Rau củ"),
 ("bi ngoi", "bí ngòi", "cuketa", "Rau củ"),
 ("ca tim", "cà tím", "lilek", "Rau củ"),
 ("cu cai", "củ cải", "redkev", "Rau củ"),
 ("cu den", "củ dền", "cervena repa", "Rau củ"),
 ("can tay", "cần tây", "celer", "Rau củ"),
 ("to i tay", "tỏi tây", "porek", "Rau củ"),
 ("mang tay", "măng tây", "chrest", "Rau củ"),
 ("dau hu", "đậu hũ", "tofu", "Rau củ"),
 ("dau phu", "đậu phụ", "tofu", "Rau củ"),
 ("gia do", "giá đỗ", "fazolove klicky", "Rau củ"),
 ("rau thom", "rau thơm", "bylinky", "Rau củ"),
 ("rau mui", "rau mùi", "koriandr", "Rau củ"),
 ("ngo ri", "ngò rí", "koriandr", "Rau củ"),
 ("hung que", "húng quế", "bazalka", "Rau củ"),
 ("thi la", "thì là", "kopr", "Rau củ"),
 # ============ TRAI CAY ============
 ("trai cay", "trái cây", "ovoce", "Trái cây"),
 ("hoa qua", "hoa quả", "ovoce", "Trái cây"),
 ("chuoi", "chuối", "banany", "Trái cây"),
 ("tao", "táo", "jablka", "Trái cây"),
 ("cam", "cam", "pomerance", "Trái cây"),
 ("quyt", "quýt", "mandarinky", "Trái cây"),
 ("chanh", "chanh", "citron", "Trái cây"),
 ("chanh xanh", "chanh xanh", "limetka", "Trái cây"),
 ("buoi", "bưởi", "grapefruit", "Trái cây"),
 ("dua hau", "dưa hấu", "meloun", "Trái cây"),
 ("dua luoi", "dưa lưới", "cukrovy meloun", "Trái cây"),
 ("dau tay", "dâu tây", "jahody", "Trái cây"),
 ("viet quat", "việt quất", "boruvky", "Trái cây"),
 ("mam xoi", "mâm xôi", "maliny", "Trái cây"),
 ("nho", "nho", "hrozny", "Trái cây"),
 ("xoai", "xoài", "mango", "Trái cây"),
 ("dua", "dừa", "kokos", "Trái cây"),
 ("thom", "thơm (dứa)", "ananas", "Trái cây"),
 ("khom", "khóm", "ananas", "Trái cây"),
 ("dua gai", "dứa", "ananas", "Trái cây"),
 ("le", "lê", "hrusky", "Trái cây"),
 ("dao", "đào", "broskve", "Trái cây"),
 ("man", "mận", "svestky", "Trái cây"),
 ("cherry", "cherry", "tresne", "Trái cây"),
 ("anh dao", "anh đào", "tresne", "Trái cây"),
 ("kiwi", "kiwi", "kiwi", "Trái cây"),
 ("qua bo", "quả bơ", "avokado", "Trái cây"),
 ("trai bo", "trái bơ", "avokado", "Trái cây"),
 ("luu", "lựu", "granatove jablko", "Trái cây"),
 ("chanh day", "chanh dây", "marakuja", "Trái cây"),
 # ============ BANH MI (pecivo) ============
 ("banh mi", "bánh mì", "chleba", "Bánh mì"),
 ("banh mi den", "bánh mì đen", "zitny chleb", "Bánh mì"),
 ("banh mi goi", "bánh mì gối", "toustovy chleb", "Bánh mì"),
 ("banh mi nho", "bánh mì nhỏ", "rohlik", "Bánh mì"),
 ("banh sung bo", "bánh sừng bò", "croissant", "Bánh mì"),
 ("banh ngot", "bánh ngọt", "kolace", "Bánh mì"),
 ("banh ran", "bánh rán", "kobliha", "Bánh mì"),
 ("banh bao ngot", "bánh bao ngọt", "buchty", "Bánh mì"),
 # ============ DO KHO & GIA VI (vareni-a-peceni, konzervy) ============
 ("gao", "gạo", "ryze", "Đồ khô & gia vị"),
 ("gao thom", "gạo thơm", "ryze jasminova", "Đồ khô & gia vị"),
 ("gao nep", "gạo nếp", "lepkava ryze", "Đồ khô & gia vị"),
 ("gao basmati", "gạo basmati", "ryze basmati", "Đồ khô & gia vị"),
 ("mi", "mì", "nudle", "Đồ khô & gia vị"),
 ("mi goi", "mì gói", "instantni nudle", "Đồ khô & gia vị"),
 ("mi tom", "mì tôm", "instantni nudle", "Đồ khô & gia vị"),
 ("mi y", "mì Ý", "spagety", "Đồ khô & gia vị"),
 ("nui", "nui", "testoviny", "Đồ khô & gia vị"),
 ("bun kho", "bún khô", "ryzove nudle", "Đồ khô & gia vị"),
 ("mien", "miến", "sklenene nudle", "Đồ khô & gia vị"),
 ("banh trang", "bánh tráng", "ryzovy papir", "Đồ khô & gia vị"),
 ("bot mi", "bột mì", "mouka", "Đồ khô & gia vị"),
 ("bot bap", "bột bắp", "kukuricny skrob", "Đồ khô & gia vị"),
 ("duong", "đường", "cukr", "Đồ khô & gia vị"),
 ("muoi", "muối", "sul", "Đồ khô & gia vị"),
 ("tieu", "tiêu", "pepr", "Đồ khô & gia vị"),
 ("dau an", "dầu ăn", "olej", "Đồ khô & gia vị"),
 ("dau huong duong", "dầu hướng dương", "slunecnicovy olej", "Đồ khô & gia vị"),
 ("dau oliu", "dầu ô liu", "olivovy olej", "Đồ khô & gia vị"),
 ("dau me", "dầu mè", "sezamovy olej", "Đồ khô & gia vị"),
 ("nuoc mam", "nước mắm", "rybi omacka", "Đồ khô & gia vị"),
 ("nuoc tuong", "nước tương", "sojova omacka", "Đồ khô & gia vị"),
 ("xi dau", "xì dầu", "sojova omacka", "Đồ khô & gia vị"),
 ("dau hao", "dầu hào", "ustricova omacka", "Đồ khô & gia vị"),
 ("tuong ot", "tương ớt", "chilli omacka", "Đồ khô & gia vị"),
 ("sriracha", "sriracha", "sriracha", "Đồ khô & gia vị"),
 ("sot ca chua", "sốt cà chua", "kecup", "Đồ khô & gia vị"),
 ("tuong ca", "tương cà", "kecup", "Đồ khô & gia vị"),
 ("mayonnaise", "mayonnaise", "majoneza", "Đồ khô & gia vị"),
 ("sot mayonnaise", "sốt mayonnaise", "majoneza", "Đồ khô & gia vị"),
 ("mu tat", "mù tạt", "horcice", "Đồ khô & gia vị"),
 ("giam", "giấm", "ocet", "Đồ khô & gia vị"),
 ("mat ong", "mật ong", "med", "Đồ khô & gia vị"),
 ("bot ngot", "bột ngọt", "glutamat", "Đồ khô & gia vị"),
 ("hat nem", "hạt nêm", "bujon", "Đồ khô & gia vị"),
 ("vien sup", "viên súp", "bujon", "Đồ khô & gia vị"),
 ("nuoc cot dua", "nước cốt dừa", "kokosove mleko", "Đồ khô & gia vị"),
 ("dau phong", "đậu phộng", "arasidy", "Đồ khô & gia vị"),
 ("lac", "lạc", "arasidy", "Đồ khô & gia vị"),
 ("hat dieu", "hạt điều", "kesu", "Đồ khô & gia vị"),
 ("hanh nhan", "hạnh nhân", "mandle", "Đồ khô & gia vị"),
 ("oc cho", "óc chó", "vlasske orechy", "Đồ khô & gia vị"),
 ("dau lang", "đậu lăng", "cocka", "Đồ khô & gia vị"),
 ("dau do", "đậu đỏ", "cervene fazole", "Đồ khô & gia vị"),
 ("dau den", "đậu đen", "cerne fazole", "Đồ khô & gia vị"),
 ("dau xanh", "đậu xanh", "mungo", "Đồ khô & gia vị"),
 ("yen mach", "yến mạch", "ovesne vlocky", "Đồ khô & gia vị"),
 ("ca hop", "cá hộp", "rybicky v konzerve", "Đồ khô & gia vị"),
 ("ca ngu hop", "cá ngừ hộp", "tunak v konzerve", "Đồ khô & gia vị"),
 ("do hop", "đồ hộp", "konzervy", "Đồ khô & gia vị"),
 ("ngo hop", "ngô hộp", "kukurice sterilovana", "Đồ khô & gia vị"),
 ("dua chuot muoi", "dưa chuột muối", "kysele okurky", "Đồ khô & gia vị"),
 ("oliu", "ô liu", "olivy", "Đồ khô & gia vị"),
 # ============ DONG LANH & AN LIEN (mrazene-a-instantni-potraviny) ============
 ("do dong lanh", "đồ đông lạnh", "mrazene", "Đông lạnh"),
 ("rau dong lanh", "rau đông lạnh", "mrazena zelenina", "Đông lạnh"),
 ("pizza dong lanh", "pizza đông lạnh", "mrazena pizza", "Đông lạnh"),
 ("pizza", "pizza", "pizza", "Đông lạnh"),
 ("khoai tay chien dong lanh", "khoai tây chiên đông lạnh", "hranolky", "Đông lạnh"),
 ("kem", "kem (ăn)", "zmrzlina", "Đông lạnh"),
 ("kem que", "kem que", "nanuk", "Đông lạnh"),
 ("ca vien", "cá viên", "rybi prsty", "Đông lạnh"),
 ("sup an lien", "súp ăn liền", "instantni polevka", "Đông lạnh"),
 # ============ BANH KEO (sladkosti-a-slane-snacky) ============
 ("banh keo", "bánh kẹo", "sladkosti", "Bánh kẹo"),
 ("keo", "kẹo", "bonbony", "Bánh kẹo"),
 ("keo deo", "kẹo dẻo", "zele bonbony", "Bánh kẹo"),
 ("keo cao su", "kẹo cao su", "zvykacky", "Bánh kẹo"),
 ("socola", "sô-cô-la", "cokolada", "Bánh kẹo"),
 ("so co la", "sô cô la", "cokolada", "Bánh kẹo"),
 ("banh quy", "bánh quy", "susenky", "Bánh kẹo"),
 ("banh xop", "bánh xốp", "oplatky", "Bánh kẹo"),
 ("khoai tay chien goi", "khoai tây chiên gói", "chipsy", "Bánh kẹo"),
 ("bim bim", "bim bim", "chipsy", "Bánh kẹo"),
 ("snack", "snack", "chipsy", "Bánh kẹo"),
 ("hat huong duong", "hạt hướng dương", "slunecnicova seminka", "Bánh kẹo"),
 ("banh gao", "bánh gạo", "ryzove chlebicky", "Bánh kẹo"),
 ("banh gato", "bánh gato", "dort", "Bánh kẹo"),
 ("banh kem", "bánh kem", "dort", "Bánh kẹo"),
 # ============ DO UONG (nealko-napoje, kava) ============
 ("nuoc", "nước", "voda", "Đồ uống"),
 ("nuoc khoang", "nước khoáng", "mineralni voda", "Đồ uống"),
 ("nuoc suoi", "nước suối", "mineralni voda", "Đồ uống"),
 ("nuoc co ga", "nước có ga", "sycena voda", "Đồ uống"),
 ("nuoc ngot", "nước ngọt", "limonada", "Đồ uống"),
 ("coca", "coca", "coca cola", "Đồ uống"),
 ("pepsi", "pepsi", "pepsi", "Đồ uống"),
 ("fanta", "fanta", "fanta", "Đồ uống"),
 ("sprite", "sprite", "sprite", "Đồ uống"),
 ("kofola", "kofola", "kofola", "Đồ uống"),
 ("nuoc cam", "nước cam", "pomerancovy dzus", "Đồ uống"),
 ("nuoc ep", "nước ép", "dzus", "Đồ uống"),
 ("nuoc tao", "nước táo", "jablecny dzus", "Đồ uống"),
 ("nuoc tang luc", "nước tăng lực", "energeticky napoj", "Đồ uống"),
 ("nuoc dua", "nước dừa", "kokosova voda", "Đồ uống"),
 ("tra da dong chai", "trà đá đóng chai", "ledovy caj", "Đồ uống"),
 ("ca phe", "cà phê", "kava", "Đồ uống"),
 ("ca phe hoa tan", "cà phê hòa tan", "instantni kava", "Đồ uống"),
 ("ca phe hat", "cà phê hạt", "zrnkova kava", "Đồ uống"),
 ("ca phe xay", "cà phê xay", "mleta kava", "Đồ uống"),
 ("tra", "trà", "caj", "Đồ uống"),
 ("che", "chè (trà)", "caj", "Đồ uống"),
 ("tra xanh", "trà xanh", "zeleny caj", "Đồ uống"),
 ("tra den", "trà đen", "cerny caj", "Đồ uống"),
 ("tra hoa qua", "trà hoa quả", "ovocny caj", "Đồ uống"),
 ("siro", "si rô", "sirup", "Đồ uống"),
 # ============ BIA - RUOU (pivo, alkohol) ============
 ("bia", "bia", "pivo", "Bia rượu"),
 ("bia lon", "bia lon", "pivo plech", "Bia rượu"),
 ("bia chai", "bia chai", "pivo sklo", "Bia rượu"),
 ("bia khong con", "bia không cồn", "nealkoholicke pivo", "Bia rượu"),
 ("ruou vang", "rượu vang", "vino", "Bia rượu"),
 ("vang do", "vang đỏ", "cervene vino", "Bia rượu"),
 ("vang trang", "vang trắng", "bile vino", "Bia rượu"),
 ("prosecco", "prosecco", "prosecco", "Bia rượu"),
 ("sampanh", "sâm panh", "sekt", "Bia rượu"),
 ("ruou", "rượu", "alkohol", "Bia rượu"),
 ("ruou manh", "rượu mạnh", "vodka", "Bia rượu"),
 ("vodka", "vodka", "vodka", "Bia rượu"),
 ("whisky", "whisky", "whisky", "Bia rượu"),
 ("rum", "rum", "rum", "Bia rượu"),
 ("gin", "gin", "gin", "Bia rượu"),
 ("becherovka", "becherovka", "becherovka", "Bia rượu"),
 ("slivovice", "slivovice (rượu mận)", "slivovice", "Bia rượu"),
 # ============ DROGERIE ============
 ("giay ve sinh", "giấy vệ sinh", "toaletni papir", "Drogerie"),
 ("khan giay", "khăn giấy", "ubrousky", "Drogerie"),
 ("giay lau bep", "giấy lau bếp", "kuchynske utirky", "Drogerie"),
 ("bot giat", "bột giặt", "praci prasek", "Drogerie"),
 ("nuoc giat", "nước giặt", "praci gel", "Drogerie"),
 ("vien giat", "viên giặt", "praci kapsle", "Drogerie"),
 ("nuoc xa vai", "nước xả vải", "avivaz", "Drogerie"),
 ("nuoc rua chen", "nước rửa chén", "prostredek na nadobi", "Drogerie"),
 ("vien rua bat", "viên rửa bát", "tablety do mycky", "Drogerie"),
 ("nuoc lau nha", "nước lau nhà", "cistic podlah", "Drogerie"),
 ("nuoc lau kinh", "nước lau kính", "cistic oken", "Drogerie"),
 ("nuoc tay", "nước tẩy", "savo", "Drogerie"),
 ("tay wc", "tẩy WC", "wc cistic", "Drogerie"),
 ("dau goi", "dầu gội", "sampon", "Drogerie"),
 ("dau xa", "dầu xả", "kondicioner", "Drogerie"),
 ("sua tam", "sữa tắm", "sprchovy gel", "Drogerie"),
 ("xa phong", "xà phòng", "mydlo", "Drogerie"),
 ("kem danh rang", "kem đánh răng", "zubni pasta", "Drogerie"),
 ("ban chai danh rang", "bàn chải đánh răng", "zubni kartacek", "Drogerie"),
 ("nuoc suc mieng", "nước súc miệng", "ustni voda", "Drogerie"),
 ("khu mui", "khử mùi", "deodorant", "Drogerie"),
 ("lan nach", "lăn nách", "deodorant", "Drogerie"),
 ("dao cao rau", "dao cạo râu", "holici strojek", "Drogerie"),
 ("bot cao rau", "bọt cạo râu", "pena na holeni", "Drogerie"),
 ("bang ve sinh", "băng vệ sinh", "damske vlozky", "Drogerie"),
 ("tampon", "tampon", "tampony", "Drogerie"),
 ("chong muoi", "chống muỗi", "proti komarum", "Drogerie"),
 ("xit muoi", "xịt muỗi", "sprej proti hmyzu", "Drogerie"),
 # ============ LAM DEP (krasa) ============
 ("kem duong da", "kem dưỡng da", "pletovy krem", "Làm đẹp"),
 ("kem chong nang", "kem chống nắng", "opalovaci krem", "Làm đẹp"),
 ("sua rua mat", "sữa rửa mặt", "cistici gel na oblicej", "Làm đẹp"),
 ("nuoc hoa", "nước hoa", "parfem", "Làm đẹp"),
 ("son moi", "son môi", "rtenka", "Làm đẹp"),
 ("kem duong the", "kem dưỡng thể", "telove mleko", "Làm đẹp"),
 ("mat na", "mặt nạ", "pletova maska", "Làm đẹp"),
 ("thuoc nhuom toc", "thuốc nhuộm tóc", "barva na vlasy", "Làm đẹp"),
 ("keo xit toc", "keo xịt tóc", "lak na vlasy", "Làm đẹp"),
 # ============ ME & BE (pro-deti, pleny) ============
 ("ta", "tã", "plenky", "Mẹ & bé"),
 ("bim", "bỉm", "plenky", "Mẹ & bé"),
 ("ta em be", "tã em bé", "plenky", "Mẹ & bé"),
 ("khan uot", "khăn ướt", "vlhcene ubrousky", "Mẹ & bé"),
 ("sua cong thuc", "sữa công thức", "kojenecke mleko", "Mẹ & bé"),
 ("bot an dam", "bột ăn dặm", "detska kase", "Mẹ & bé"),
 ("do an em be", "đồ ăn em bé", "detska vyziva", "Mẹ & bé"),
 ("binh sua", "bình sữa", "kojenecka lahev", "Mẹ & bé"),
 # ============ THU CUNG (mazlicci) ============
 ("do cho", "đồ chó", "pro psy", "Thú cưng"),
 ("do an cho cho", "đồ ăn cho chó", "pro psy", "Thú cưng"),
 ("thuc an cho", "thức ăn chó", "pro psy", "Thú cưng"),
 ("hat cho cho", "hạt cho chó", "granule", "Thú cưng"),
 ("pate cho", "pa tê chó", "konzerva pro psy", "Thú cưng"),
 ("do meo", "đồ mèo", "pro kocky", "Thú cưng"),
 ("do an cho meo", "đồ ăn cho mèo", "pro kocky", "Thú cưng"),
 ("thuc an meo", "thức ăn mèo", "pro kocky", "Thú cưng"),
 ("hat cho meo", "hạt cho mèo", "granule", "Thú cưng"),
 ("pate meo", "pa tê mèo", "kapsicky pro kocky", "Thú cưng"),
 ("cat ve sinh", "cát vệ sinh", "stelivo", "Thú cưng"),
 # ============ GIA DUNG & KHAC (domacnost, elektro, lekarna...) ============
 ("pin", "pin", "baterie", "Gia dụng & khác"),
 ("bong den", "bóng đèn", "zarovka", "Gia dụng & khác"),
 ("tui rac", "túi rác", "pytle na odpad", "Gia dụng & khác"),
 ("giay bac", "giấy bạc", "alobal", "Gia dụng & khác"),
 ("mang boc thuc pham", "màng bọc thực phẩm", "potravinova folie", "Gia dụng & khác"),
 ("nen", "nến", "svicky", "Gia dụng & khác"),
 ("khan tam", "khăn tắm", "rucnik", "Gia dụng & khác"),
 ("noi", "nồi", "hrnec", "Gia dụng & khác"),
 ("chao", "chảo", "panev", "Gia dụng & khác"),
 ("vitamin", "vitamin", "vitaminy", "Gia dụng & khác"),
 ("thuoc giam dau", "thuốc giảm đau", "paralen", "Gia dụng & khác"),
 ("khau trang", "khẩu trang", "rousky", "Gia dụng & khác"),
 ("do choi", "đồ chơi", "hracky", "Gia dụng & khác"),
 ("but", "bút", "propiska", "Gia dụng & khác"),
 ("vo", "vở", "sesit", "Gia dụng & khác"),
 # ============ DO CHAU A (Tamda Express - bo sung 07/2026) ============
 ("bun", "bún", "ryzove nudle", "Đồ châu Á"),
 ("banh pho", "bánh phở", "pho nudle", "Đồ châu Á"),
 ("pho", "phở", "pho", "Đồ châu Á"),
 ("hu tieu", "hủ tiếu", "ryzove nudle", "Đồ châu Á"),
 ("mi udon", "mì udon", "udon", "Đồ châu Á"),
 ("mi soba", "mì soba", "soba", "Đồ châu Á"),
 ("mi ramen", "mì ramen", "ramen", "Đồ châu Á"),
 ("banh da nem", "bánh đa nem", "ryzovy papir", "Đồ châu Á"),
 ("mien dong", "miến dong", "sklenene nudle", "Đồ châu Á"),
 ("bot nang", "bột năng", "tapiokovy skrob", "Đồ châu Á"),
 ("bot gao", "bột gạo", "ryzova mouka", "Đồ châu Á"),
 ("bot nep", "bột nếp", "lepkava ryzova mouka", "Đồ châu Á"),
 ("tuong den", "tương đen", "hoisin", "Đồ châu Á"),
 ("sa te", "sa tế", "sate", "Đồ châu Á"),
 ("mam tom", "mắm tôm", "krevetova pasta", "Đồ châu Á"),
 ("mam ruoc", "mắm ruốc", "krevetova pasta", "Đồ châu Á"),
 ("chao", "chao (đậu hũ muối)", "fermentovane tofu", "Đồ châu Á"),
 ("wasabi", "wasabi", "wasabi", "Đồ châu Á"),
 ("rong bien", "rong biển", "morske rasy", "Đồ châu Á"),
 ("la nori", "lá nori", "nori", "Đồ châu Á"),
 ("kim chi", "kim chi", "kimchi", "Đồ châu Á"),
 ("mang", "măng", "bambusove vyhonky", "Đồ châu Á"),
 ("nam meo", "nấm mèo", "jidas usi", "Đồ châu Á"),
 ("nam dong co", "nấm đông cô", "shiitake", "Đồ châu Á"),
 ("sa", "sả", "citronova trava", "Đồ châu Á"),
 ("la chanh", "lá chanh", "kaffir", "Đồ châu Á"),
 ("rieng", "riềng", "galangal", "Đồ châu Á"),
 ("nghe", "nghệ", "kurkuma", "Đồ châu Á"),
 ("que", "quế", "skorice", "Đồ châu Á"),
 ("hoi", "hồi", "badyan", "Đồ châu Á"),
 ("dinh huong", "đinh hương", "hrebicek", "Đồ châu Á"),
 ("ngu vi huong", "ngũ vị hương", "pet koreni", "Đồ châu Á"),
 ("bot ca ri", "bột cà ri", "kari", "Đồ châu Á"),
 ("ca ri", "cà ri", "kari", "Đồ châu Á"),
 ("me chua", "me (quả)", "tamarind", "Đồ châu Á"),
 ("dau do do", "đậu đỏ đỗ", "adzuki", "Đồ châu Á"),
 ("hat sen", "hạt sen", "lotosova seminka", "Đồ châu Á"),
 ("nuoc dua tuoi", "nước dừa tươi", "kokosova voda", "Đồ châu Á"),
 ("sua dau nanh", "sữa đậu nành", "sojove mleko", "Đồ châu Á"),
 ("tra sua", "trà sữa", "bubble tea", "Đồ châu Á"),
 ("tran chau", "trân châu", "tapioka perly", "Đồ châu Á"),
 ("gio lua", "giò lụa", "vietnamska sunka", "Đồ châu Á"),
 ("nem chua", "nem chua", "nem chua", "Đồ châu Á"),
 ("cha gio", "chả giò", "jarni zavitky", "Đồ châu Á"),
 ("nem ran", "nem rán", "jarni zavitky", "Đồ châu Á"),
 ("banh bao", "bánh bao", "parene knedliky", "Đồ châu Á"),
 ("dim sum", "dim sum", "dim sum", "Đồ châu Á"),
 ("dau hu chien", "đậu hũ chiên", "smazene tofu", "Đồ châu Á"),
 ("mi a one", "mì A-One", "a-one", "Đồ châu Á"),
 ("mi hao hao", "mì Hảo Hảo", "hao hao", "Đồ châu Á"),
 ("mi vi phở", "mì vị phở", "pho nudle instantni", "Đồ châu Á"),
 # ============ RAU CHAU A ============
 ("rau muong", "rau muống", "vodni spenat", "Rau củ"),
 ("cai ngot", "cải ngọt", "pak choi", "Rau củ"),
 ("cai chip", "cải chíp", "pak choi", "Rau củ"),
 ("cai be xanh", "cải bẹ xanh", "horcicne listy", "Rau củ"),
 ("su hao", "su hào", "kedlubna", "Rau củ"),
 ("su su", "su su", "chayote", "Rau củ"),
 ("dau bap", "đậu bắp", "okra", "Rau củ"),
 ("kho qua", "khổ qua", "horka okurka", "Rau củ"),
 ("muop dang", "mướp đắng", "horka okurka", "Rau củ"),
 ("khoai mon", "khoai môn", "taro", "Rau củ"),
 ("khoai mi", "khoai mì", "maniok", "Rau củ"),
 ("san", "sắn", "maniok", "Rau củ"),
 # ============ THIT CA BO SUNG (Bidfood gastro) ============
 ("thit de", "thịt dê", "kozi maso", "Thịt cá"),
 ("dui vit", "đùi vịt", "kachni stehna", "Thịt cá"),
 ("uc vit", "ức vịt", "kachni prsa", "Thịt cá"),
 ("trung vit", "trứng vịt", "kachni vejce", "Thịt cá"),
 ("long ga", "lòng gà", "kureci drupky", "Thịt cá"),
 ("me ga", "mề gà", "kureci zaludky", "Thịt cá"),
 ("tim heo", "tim heo", "veprove srdce", "Thịt cá"),
 ("long heo", "lòng heo", "veprove drupky", "Thịt cá"),
 ("duoi bo", "đuôi bò", "hovezi ohon", "Thịt cá"),
 ("xuong bo", "xương bò", "hovezi kosti", "Thịt cá"),
 ("xuong heo", "xương heo", "veprove kosti", "Thịt cá"),
 ("bap bo", "bắp bò", "hovezi klizka", "Thịt cá"),
 ("luon", "lươn", "uhor", "Thịt cá"),
 ("ca ro phi", "cá rô phi", "tilapie", "Thịt cá"),
 ("bach tuoc", "bạch tuộc", "chobotnice", "Thịt cá"),
 ("ngheu", "nghêu", "slavky", "Thịt cá"),
 ("so", "sò", "slavky", "Thịt cá"),
 ("hau", "hàu", "ustrice", "Thịt cá"),
 ("ech", "ếch", "zabi stehna", "Thịt cá"),
 ("tom su", "tôm sú", "tygri krevety", "Thịt cá"),
 ("tom the", "tôm thẻ", "krevety vannamei", "Thịt cá"),
 # ============ BIA SEC PHO BIEN ============
 ("bia kozel", "bia Kozel", "kozel", "Bia rượu"),
 ("bia pilsner", "bia Pilsner", "pilsner urquell", "Bia rượu"),
 ("bia gambrinus", "bia Gambrinus", "gambrinus", "Bia rượu"),
 ("bia radegast", "bia Radegast", "radegast", "Bia rượu"),
 ("bia staropramen", "bia Staropramen", "staropramen", "Bia rượu"),
 ("bia birell", "bia Birell (không cồn)", "birell", "Bia rượu"),
 # ============ KHAC ============
 ("sua dac tatra", "sữa đặc Tatra", "tatra piknik", "Sữa & trứng"),
 ("pho mai parmesan", "phô mai parmesan", "parmezan", "Sữa & trứng"),
 ("da vien", "đá viên", "led", "Gia dụng & khác"),
 ("than nuong", "than nướng", "grilovaci uhli", "Gia dụng & khác"),
 ("giay nuong", "giấy nướng", "pecici papir", "Gia dụng & khác"),
 ("hop dung thuc an", "hộp đựng thức ăn", "dozy na potraviny", "Gia dụng & khác"),
 # ============ BO SUNG THONG MINH 07/2026 — nguoi Viet hay tim ============
 # --- Rau thom / la ---
 ("la lot", "lá lốt", "piper lolot listy", "Rau củ"),
 ("tia to", "tía tô", "perilla listy", "Rau củ"),
 ("kinh gioi", "kinh giới", "vietnamska majoranka", "Rau củ"),
 ("hung lui", "húng lủi", "mata", "Rau củ"),
 ("bac ha", "bạc hà", "mata", "Rau củ"),
 ("rau ram", "rau răm", "rdesno", "Rau củ"),
 ("ngo gai", "ngò gai", "kulantro", "Rau củ"),
 ("thi la", "thì là", "kopr", "Rau củ"),
 ("la mo", "lá mơ", "paederia listy", "Rau củ"),
 ("la chuoi", "lá chuối", "bananove listy", "Rau củ"),
 ("hoa chuoi", "hoa chuối", "bananovy kvet", "Rau củ"),
 ("bap chuoi", "bắp chuối", "bananovy kvet", "Rau củ"),
 ("ngo sen", "ngó sen", "lotosove stonky", "Rau củ"),
 # --- Rau cu ---
 ("muop", "mướp", "tikev hadovita", "Rau củ"),
 ("muop huong", "mướp hương", "tikev hadovita", "Rau củ"),
 ("bau", "bầu", "tykev lahvovita", "Rau củ"),
 ("bi xanh", "bí xanh", "vinna tykev", "Rau củ"),
 ("bi dao", "bí đao", "vinna tykev", "Rau củ"),
 ("cai xanh", "cải xanh", "horcicne listy", "Rau củ"),
 ("cai ngong", "cải ngồng", "choy sum", "Rau củ"),
 ("mong toi", "mồng tơi", "malabarsky spenat", "Rau củ"),
 ("rau day", "rau đay", "jutove listy", "Rau củ"),
 ("rau ngot", "rau ngót", "sladke listy", "Rau củ"),
 ("rau den", "rau dền", "amarant listy", "Rau củ"),
 ("cu dau", "củ đậu", "jicama", "Rau củ"),
 ("cu sen", "củ sen", "lotosovy koren", "Rau củ"),
 ("nam rom", "nấm rơm", "slamova houba", "Rau củ"),
 ("nam kim cham", "nấm kim châm", "enoki", "Rau củ"),
 ("nam bao ngu", "nấm bào ngư", "hlivova houba", "Rau củ"),
 ("nam tuyet", "nấm tuyết", "bila houba", "Rau củ"),
 # --- Hai san ---
 ("oc", "ốc", "hlemyzdi", "Thịt cá"),
 ("ghe", "ghẹ", "krab", "Thịt cá"),
 ("so huyet", "sò huyết", "krvave mušle", "Thịt cá"),
 ("tep", "tép", "male krevety", "Thịt cá"),
 ("ca loc", "cá lóc", "hadi ryba", "Thịt cá"),
 ("ca tre", "cá trê", "sumec", "Thịt cá"),
 ("ca dieu hong", "cá diêu hồng", "tilapie cervena", "Thịt cá"),
 ("ca keo", "cá kèo", "hlavacovita ryba", "Thịt cá"),
 ("tom kho", "tôm khô", "susene krevety", "Thịt cá"),
 ("muc kho", "mực khô", "susena olihen", "Thịt cá"),
 ("ca kho", "cá khô", "susena ryba", "Thịt cá"),
 # --- Thit ---
 ("thit vai", "thịt vai", "veprova plec", "Thịt cá"),
 ("nam long", "nạm lòng", "hovezi bok", "Thịt cá"),
 ("gan lon", "gân lợn", "veprove slachy", "Thịt cá"),
 ("da lon", "da lợn", "veprova kuze", "Thịt cá"),
 ("suon non", "sườn non", "veprova zebirka", "Thịt cá"),
 ("mong gio", "móng giò", "veprove nozicky", "Thịt cá"),
 # --- Dac san / che bien ---
 ("nem", "nem", "jarni zavitky", "Đồ châu Á"),
 ("cha lua", "chả lụa", "vietnamska sunka", "Đồ châu Á"),
 ("gio cha", "giò chả", "vietnamska sunka", "Đồ châu Á"),
 ("cha que", "chả quế", "skoricova sunka", "Đồ châu Á"),
 ("banh da", "bánh đa", "ryzove chlebicky", "Đồ châu Á"),
 ("banh hoi", "bánh hỏi", "tenke ryzove nudle", "Đồ châu Á"),
 ("banh canh", "bánh canh", "silne ryzove nudle", "Đồ châu Á"),
 ("bun tuoi", "bún tươi", "cerstve ryzove nudle", "Đồ châu Á"),
 ("mam nem", "mắm nêm", "rybi pasta", "Đồ châu Á"),
 ("mam tep", "mắm tép", "krevetova pasta", "Đồ châu Á"),
 ("sa te", "sa tế", "sate chilli", "Đồ châu Á"),
 ("tuong ban", "tương bần", "sojova pasta", "Đồ châu Á"),
 ("dau phu ky", "đậu phụ ky", "susena tofu koze", "Đồ châu Á"),
 ("tau hu ky", "tàu hũ ky", "susena tofu koze", "Đồ châu Á"),
 # --- Do kho / gia vi ---
 ("long nhan", "long nhãn", "susene longany", "Đồ khô & gia vị"),
 ("tao tau", "táo tàu", "cervene datle jujube", "Đồ khô & gia vị"),
 ("ky tu", "kỷ tử", "goji", "Đồ khô & gia vị"),
 ("bot bang", "bột báng", "tapiokove kulicky", "Đồ khô & gia vị"),
 ("bot khoai", "bột khoai", "tapiokovy skrob", "Đồ khô & gia vị"),
 ("mang kho", "măng khô", "susene bambusove vyhonky", "Đồ khô & gia vị"),
 ("mang chua", "măng chua", "nakladane bambusove vyhonky", "Đồ khô & gia vị"),
 ("dua muoi", "dưa muối", "nakladana zelenina", "Đồ khô & gia vị"),
 ("ca muoi", "cà muối", "nakladane liliky", "Đồ khô & gia vị"),
 ("hat sen kho", "hạt sen khô", "susena lotosova seminka", "Đồ khô & gia vị"),
 # --- Pho / bun ---
 ("pho", "phở", "pho ryzove nudle", "Đồ châu Á"),
 ("bun bo", "bún bò", "hovezi pho", "Đồ châu Á"),
 ("mien mang", "miến măng", "sklenene nudle", "Đồ châu Á"),
]

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Tu dien Viet-Sec"
ws.append(["Tieng Viet (khong dau)", "Tiếng Việt (có dấu)", "Tiếng Séc (từ khóa tìm)", "Nhóm hàng"])
for c in ws[1]:
    c.font = Font(bold=True, color="FFFFFF")
    c.fill = PatternFill("solid", fgColor="B96A1E")
for row in E:
    ws.append(list(row))
for col, w in zip("ABCD", [28, 30, 32, 18]):
    ws.column_dimensions[col].width = w
ws.freeze_panes = "A2"
wb.save("tudien.xlsx")
print(f"Da tao tudien.xlsx voi {len(E)} muc tu")
